version: 2
updates:
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Moscow
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Moscow

